# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homecook-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homecook-frontend
  template:
    metadata:
      labels:
        app: homecook-frontend
    spec:
      containers:
      - name: homecook-frontend
        image: localhost:5000/homecook-connect:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://homecook-backend:300811"
          