apiVersion: apps/v1
kind: Deployment
metadata:
  name: homecook-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homecook-frontend
  template:
    metadata:
      labels:
        app: homecook-frontend
    spec:
      containers:
      - name: homecook-frontend
        image: localhost:5001/homecook-frontend:latest
        imagePullPolicy: Never
        env:
        - name: VITE_API_URL
          value: "http://localhost:30081"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: nginx-temp
          mountPath: /tmp/nginx
        - name: nginx-run
          mountPath: /var/run/nginx
        - name: nginx-cache
          mountPath: /var/cache/nginx
        securityContext:
          runAsUser: 101
          runAsGroup: 101
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-temp
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {} 