apiVersion: v1
kind: Service
metadata:
  name: homecook-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # This will be accessible on localhost:30080
  selector:
    app: homecook-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: homecook-backend
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30081  # Backend will be accessible on localhost:30081
  selector:
    app: homecook-backend